## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
print("basic Slicnig", arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing", arr [-3])

basic Slicnig [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [3]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element :", arr_2D[2,2])
print("Entire row: ", arr_2D[1])
print("Entire row: ", arr_2D[:,2])

Specific Element : 9
Entire row:  [4 5 6]
Entire row:  [3 6 9]


## Sorting

In [4]:
unsorted = np.array([3,57,3,97,45,23,1,45,66,232,43,21,456,9,7])
print("Sorted Array :", np.sort(unsorted))

arr_2d_unsorted = np.array([[24,48,28],
                           [23,43,17],
                           [28,18,39]])
print("Sorted 2D array by row : \n", np.sort(arr_2d_unsorted, axis=0))

Sorted Array : [  1   3   3   7   9  21  23  43  45  45  57  66  97 232 456]
Sorted 2D array by row : 
 [[23 18 17]
 [24 43 28]
 [28 48 39]]


## Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8,  9, 10])
even_number = numbers[numbers % 2==0]
print("Even number : \n", even_number)

Even number : 
 [ 2  4  6  8 10]


## Filter with mask

In [6]:
mask = numbers > 5
print("Number greater then 5 :", numbers[mask])

Number greater then 5 : [ 6  7  8  9 10]


## Fancy indexing vs np.where()  

In [7]:
indices = [0 ,2 , 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and removing data

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shap", a.shape == b.shape)

Compatibility shap True


In [24]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6],[7,8]])
with_new_row = np.vstack((original, new_row))
print(original )
print(with_new_row)

new_col =np.array([[7], [9]])
with_new_col = np.hstack((original , new_col))
print("With new column : \n " , with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
With new column : 
  [[1 2 7]
 [3 4 9]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5 6 7 8]
