## Numpy array and basice
learn about  numoy with chai aur code

In [3]:
import numpy as np

### creating array from list

In [23]:
arr_1d = np.array ([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr_2d)

1D array:  [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1,2,3]
print("python array multiplication", py_list *2)

np_array = np.array([1,2,3])
print("Python array multiplication", np_array *2)

import time 
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List operation time: ", time .time() - start)

start = time.time()
np_array = np.arange(100000000)*2
print("\n Numpy operation time: ", time .time() - start)

python array multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time:  4.01291298866272

 Numpy operation time:  0.48122668266296387


### Craeating array form scratch

In [23]:
zeros = np.zeros ((3,4))
print("zeros array: \n", zeros)

ones = np.ones ((7,9))
print("ones array: \n", ones)

full = np.full((4,6), 8)
print("full array: \n", full)

random = np.random.random ((6,3))
print ("random array: \n", random)

sequence = np.arange(0,10,2)
print("sequnce array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
full array: 
 [[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]
random array: 
 [[0.67978745 0.60907428 0.35551206]
 [0.54043963 0.17923141 0.24067386]
 [0.10162441 0.39904851 0.55156224]
 [0.6855682  0.29203313 0.05810181]
 [0.93029548 0.40233038 0.44026708]
 [0.85181714 0.33917405 0.1276319 ]]
sequnce array: 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: \n ", tensor)

vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [30]:
arr = np.array([[1,2,3],
                [4,5,"4.3"]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  <U21


### Array Reshaping

In [38]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped ", reshaped) 

flattened = reshaped.flatten()
print("\n Flattened array", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose array ", transpose)



Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
