## Numpy array and basice
learn about  numoy with chai aur code

In [16]:
import numpy as np

### creating array from list

In [23]:
arr_1d = np.array ([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: \n", arr_2d)

1D array:  [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [6]:
py_list = [1,2,3]
print("python array multiplication", py_list *2)

np_array = np.array([1,2,3])
print("Pyton array multiplication", np_array *2)

import time 
start = time.time()
py_list = [i*2 for i in range(100000000)]
print("\n List operation time: ", time .time() - start)

start = time.time()
np_array = np.arange(100000000)*2
print("\n Numpy operation time: ", time .time() - start)

python array multiplication [1, 2, 3, 1, 2, 3]
Pyton array multiplication [2 4 6]

 List operation time:  3.326500415802002

 Numpy operation time:  0.3002810478210449


### Craeating array form scratch

In [22]:
zeros = np.zeros ((3,4))
print("zeros array: \n", zeros)

ones = np.ones ((7,9))
print("ones array: \n", ones)

full = np.full((4,6), 8)
print("full array: \n", full)

random = np.random.random ((6,3))
print ("random array: \n", random)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
full array: 
 [[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]
random array: 
 [[0.91231829 0.72515876 0.26023797]
 [0.68679875 0.61937859 0.24774464]
 [0.86744663 0.005659   0.84589093]
 [0.90311798 0.58923147 0.09136478]
 [0.47758657 0.56189032 0.95815019]
 [0.77486918 0.58827347 0.77696598]]
